### ISSUE TITLE
Can you add request matching by json content?

### ISSUE THREAD

**Issue by fbachan** [friendsofgo/killgrave#120]

**Comment by joanlopez** [comment]
Hi @fbachan, thanks for reaching us! 

Have seen the support for JSON schema? 👇🏻 
https://github.com/friendsofgo/killgrave#create-an-imposter-using-json-schema

If so, and still not enough.
Can you share some examples about what do you actually need and why JSON schema support is not enough? 

Thanks!

**Comment by joanlopez** [comment]
Hey @fbachan, I'm doing some cleanup here, so as we received no news in more than one year, I'm going to close this issue for now. But feel free to re-open it, or create a new one if you have any remaining doubts or questions.

Thanks!
