### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by diegolagospagopa** [friendsofgo/killgrave#124]
I start by telling you that your project is fantastic, I just wanted to know its status since there are some PR not included yet and the last commit is from September 2021.

Thanks so much

**Comment by joanlopez** [comment]
Hello @diegolagospagopa,

Thanks for your feedback! Yeah, it's true (and a bit sad) that we've been inactive almost during last whole year. 
However, we're doing a bit of backlog clean up, prioritization so I'm happy to share with you that we're on the way to be back.

:)

**Comment by joanlopez** [comment]
Finally, we're back! @diegolagospagopa 🎉
