### ISSUE TITLE
multi-arch docker images request

### ISSUE THREAD

**Issue by flabatut** [friendsofgo/killgrave#162]
is it possible to release multi platform/arch docker images ?
pretty easy to implement with github actions: https://docs.docker.com/build/ci/github-actions/multi-platform/
Whether agreed, PR accepted ?

**Comment by joanlopez** [comment]
Hey @flabatut,

> is it possible to release multi platform/arch docker images ?

Yeah, that would be something nice to have.

> Whether agreed, PR accepted ?

Of course, contributions are more than welcome! 😄 

Thanks so much! 🙏🏻

**Comment by joanlopez** [comment]
Closed by #163
