### ISSUE TITLE
Query params

### ISSUE THREAD

**Issue by ivandemingo23** [friendsofgo/killgrave#2]
Además de indicar el _path_ del _endpoint_, sería útil que se pudiera añadir _query params_.

Sugerencia: Según he visto en la documentación de Gorilla Mux (https://github.com/gorilla/mux#matching-routes), se pueden añadir _query params_ al _router_ de la siguiente manera:

```go
r.Queries("key", "value")
```

**Comment by aperezg** [comment]
Entiendo que lo que pides, es poder realizar responses dinámicas a partir de unos *query params*, al igual que se hace con el *endpoint* dentro del *request*, ¿no?

**Comment by ivandemingo23** [comment]
Exacto!

**Comment by aperezg** [comment]
English:
Allow multiples imposters in one file, and identified by endpoint or query params, with fix values or regex.

i.e. errors, or distinct status codes, with differents body for each response
