### ISSUE TITLE
Remove pkg/errors library

### ISSUE THREAD

**Issue by aperezg** [friendsofgo/killgrave#26]
Since go1.13 version the library `pkg/errors` is depecrated in favor to errors on 1.13. IMHO I think that we don't need the extra library to handle the errors of our application, so I think that can be change all errors uses for new  `errors` packages, using sentinels or wrapping it if it's necessary.

**Comment by hassieswift621** [comment]
If you wish to use Go 1.13 errors but with backwards compatibility with older Go versions, you can use the official Go lib https://godoc.org/golang.org/x/xerrors
