### ISSUE TITLE
Allow XML schema validation on requests

### ISSUE THREAD

**Issue by joanlopez** [friendsofgo/killgrave#35]
## Context

Killgrave was initially developed as a mock server focused on JSON HTTP APIs. However, as the responses configuration is highly flexible, it could be used to return responses of almost any type. That could allow Killgrave's users to use it also to mock XML HTTP APIs.

So, to provide those potential users a great experience, we also want to allow them configure some schema (XML) validations the same way as it's currently done for JSON requests.

## Proposed implementation

The field (within imposter) to specify the file used for validation's definition can still being `schemaFile` (as it is currently for JSON validations).

The schema's file type (JSON vs XML) can be deduced from its extension (`.json` vs `.xml`) or a `schemaType` field can be eventually added.

Any suggestion about that will be welcome.

**Comment by hicks2evan** [comment]
Hi! I'm new here and looking to pick this up as a part of Hacktoberfest. I installed the project via homebrew and am experimenting with sending and receiving xml. Any suggestions for producing a build to test locally once I've made some changes?

**Comment by hicks2evan** [comment]
@joanlopez @aperezg could you take a look at this commit and verify my approach? https://github.com/hicks2evan/killgrave/commit/c3ad70a8ff96f3b3d31cb1aee55fa1a3702b6611

As for actually validating the schema of the xml request, I found this package https://godoc.org/github.com/lestrrat/go-libxml2/xsd, let me know what you think.

**Comment by joanlopez** [comment]
Hey @hicks2evan,

First, thanks for your interest in our project. We're really happy to see people like you engaging with us.
Regarding your strategy, it looks good to me. Let me ping @aperezg to get his opinion on this, but I'd say you can keep working in that direction.

Feel free to ping us if you have any additional doubt or need.

Thanks!

**Comment by hicks2evan** [comment]
Hi @joanlopez and @aperezg,
I have opened this PR https://github.com/friendsofgo/killgrave/pull/74, please review when you get the chance. Cheers!

**Comment by hicks2evan** [comment]
I tried implementing with different xml packages, but either way the circle-ci build is facing issues with the libxml-2.0 package. Not sure what I can change to make that work, have you ever seen before?

**Comment by joanlopez** [comment]
Hey @hicks2evan,

The library you used seems to be a Go binding for another XML parser, so the pipeline is complaining because it misses that dependency. So, you must add that dependency everywhere (CI runners, Docker image, etc) to get it running.

However, I'd like to try if a standalone library (e.g. [`encoding/xml`](https://golang.org/pkg/encoding/xml/)) would be enough, in order to avoid new system dependencies.

Please, feel free to reach us out as soon as you get new feedback or any additional doubt.
Thanks for your contributions!! 🙏

**Comment by hicks2evan** [comment]
Hey @joanlopez, just coming back to this. I should have time to look at it some time this week. Thank you for the feedback.

**Comment by joanlopez** [comment]
Hi @hicks2evan,
Did you have time to work on the feedback? Otherwise we'll address it.
Thanks!

**Comment by aperezg** [comment]
More info: https://github.com/friendsofgo/killgrave/pull/90#pullrequestreview-611643698
