### ISSUE TITLE
Add a CircleCI job to push each new release to DockerHub

### ISSUE THREAD

**Issue by joanlopez** [friendsofgo/killgrave#61]
The Killgrave project uses [CircleCI](https://circleci.com) for build & test pipelines (see the configuration file [here](https://github.com/friendsofgo/killgrave/blob/master/.circleci/config.yml)). Additionally, every release of Killgrave is present on [Docker Hub](https://hub.docker.com/r/friendsofgo/killgrave). So, it'd be great to add a new CircleCI step to automatically push each new release to DockerHub.

Please, notice that this new job should be filtered in the same way as the [release](https://github.com/friendsofgo/killgrave/blob/master/.circleci/config.yml#L53) one.

**Comment by exelban** [comment]
Hi.

Do you want to migrate the ci/cd to github action?

**Comment by joanlopez** [comment]
That would be even better!! 🚀 
Feel free to contribute to that migration, just let us know which environment / project variables do we need to set up.

cc/ @aperezg

**Comment by aperezg** [comment]
Closes with #62
