### ISSUE TITLE
The endpoint should work with final `/` or without it

### ISSUE THREAD

**Issue by aperezg** [friendsofgo/killgrave#89]
If we have a imposter like this:

```
[
    {
        "request": {
            "method": "GET",
            "endpoint": "/api/people/1"
        },
        "response": {
            "status": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "bodyFile": "swapi_luke.json"
        }
    }
]
```

And will try to call to this endpoint on this way: `http://localhost:3000/api/people/1/` the mock server will return a `404` because it's not matching with the `path`.

So the normal behaviour is that url ignoring if have a `/` or not and have the same behaviour

**Comment by joanlopez** [comment]
Hey @aperezg, 

I've been exploring the `gorilla/mux` documentation and I guess that calling to [`Router.StrictSlash`](https://pkg.go.dev/github.com/gorilla/mux#Router.StrictSlash) with `true` would be enough. Does that make sense for you? If so, do you think that should be configurable either by flag or configuration file?

Thanks!

**Comment by aperezg** [comment]
Do you know if that works fine with regex endpoints also?

**Comment by mdsantosdev** [comment]
> Do you know if that works fine with regex endpoints also?

It will interpret any match including the / in the value or it will not match at all.
Source: [](https://github.com/gorilla/mux/issues/30)

I'd love to contribute a solution, what I was thinking is to make Strict Slash configurable (PR on the way). Let me know your opinions.

**Comment by mdsantosdev** [comment]
PR: [https://github.com/friendsofgo/killgrave/pull/91](https://github.com/friendsofgo/killgrave/pull/91)

**Comment by martin-dos-santos** [comment]
New PR based on @aperezg opinion [https://github.com/friendsofgo/killgrave/pull/92](https://github.com/friendsofgo/killgrave/pull/92)
Let me know if you think that I can improve it in some way. Thanks.

**Comment by joanlopez** [comment]
Allowing users to configure the [`Router.StrictSlash`](https://pkg.go.dev/github.com/gorilla/mux#Router.StrictSlash) setting through Killgrave settings is something that could make sense. 

However, I'd say that's not something very frequent (users usually want both -to work with ending slash or not-), so I'd vote for following a lean approach and wait for user's feedback to see whether or not it does worth to make it configurable.

**Comment by joanlopez** [comment]
I think this needs to be part of the `v0.5.0` release (instead of `v0.4.1`) since it actually breaks (changes) the current behavior.

WDYT?

**Comment by aperezg** [comment]
Oh, you're right @joanlopez If for that that I created the issue with v0.5.0 tag, I didn't remember when I asked to @martin-dos-santos to change the version.

So, @martin-dos-santos sorry, but if you could change the base of the PR to the branch v0.5.0 will be great sorry for the mess 🙏 was my fault ^^'

**Comment by martin-dos-santos** [comment]
> Oh, you're right @joanlopez If for that that I created the issue with v0.5.0 tag, I didn't remember when I asked to @martin-dos-santos to change the version.
> 
> So, @martin-dos-santos sorry, but if you could change the base of the PR to the branch v0.5.0 will be great sorry for the mess  was my fault ^^'

Don't worry!, there we go [(https://github.com/friendsofgo/killgrave/pull/93)](https://github.com/friendsofgo/killgrave/pull/93)

**Comment by martin-dos-santos** [comment]
Looks like that branch is broken, can I do anything to solve it?

**Comment by aperezg** [comment]
Don't worry we need to remove the circle ci integration when we migrate all to the v0.5.0.

Thanks a lot for the contribution!
